<div id="edit-buttons">
  <form action="index.php">
    <input method="POST" type="submit" id="cancel" class="button" value="Reset"/>
  </form>
  <form method="POST" action="run.php">
    <input type="submit" id="run" class="button" value="Run dcp_manager.sh"/>
  </form>
  <form method="POST" action="catalog.php" target="_blank">
    <input type="submit" id="catalog" class="button" value="Catalog"/>
  </form>
  <form action="mount.php">
    <input method="POST" type="submit" id="mount" class="button" value="Mount"/>
  </form>
  <form action="umount.php">
    <input method="POST" type="submit" id="unmount" class="button" value="Un-Mount"/>
  </form>
  <form action="phpInfo.php" target="_blank">
    <input method="POST" type="submit" id="phpinfo" class="button" value="PHP Info"/>
  </form>
</div>
